# Generated by Django 5.2.17 on 2026-08-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorprofile',
            name='association_name',
        ),
        migrations.RemoveField(
            model_name='operatorprofile',
            name='operating_region',
        ),
        migrations.RemoveField(
            model_name='operatorprofile',
            name='rank_code_used',
        ),
        migrations.RemoveField(
            model_name='rankcode',
            name='is_used',
        ),
        migrations.AddField(
            model_name='operatorprofile',
            name='association',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='accounts.rankcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankcode',
            name='association_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rankcode',
            name='operating_region',
            field=models.CharField(default='TBD', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_applications', to='accounts.rankcode'),
        ),
    ]
