# Generated by Django 5.2.17 on 2026-08-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_operatorprofile_association_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='second_next_of_kin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='second_next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
