# Generated by Django 5.2.17 on 2026-09-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='external_verification_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='external_verification_status',
            field=models.CharField(choices=[('unverified', 'Not yet checked'), ('verified', 'Verified with DOT'), ('failed', 'Failed DOT verification'), ('suspended', 'Licence suspended or revoked'), ('unavailable', 'DOT registry unavailable')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='pdp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
