# Generated by Django 5.2.17 on 2026-09-20 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminprofile_rank'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAssetChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('driver_not_fit', 'Driver not fit to drive'), ('driver_responsibilities', 'Driver has other responsibilities'), ('driver_rotation', 'Driver rotation change'), ('vehicle_not_fit', 'Vehicle not fit for travel'), ('vehicle_forfeit', 'Vehicle voluntary forfeit'), ('vehicle_swap', 'Vehicle swapped in queue'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_changes_made', to=settings.AUTH_USER_MODEL)),
                ('new_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_to', to='accounts.driverprofile')),
                ('new_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_to', to='transport.vehicle')),
                ('old_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_from', to='accounts.driverprofile')),
                ('old_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_from', to='transport.vehicle')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_changes', to='transport.trip')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
