# Generated by Django 5.2.17 on 2026-09-19 00:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminprofile_rank'),
        ('transport', '0002_rank_alter_departurepoint_name_departurepoint_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departurepoint',
            options={'ordering': ['rank__name']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['departure_point__rank__name', 'destination__name']},
        ),
        migrations.AlterUniqueTogether(
            name='departurepoint',
            unique_together={('operator', 'rank')},
        ),
        migrations.AddField(
            model_name='departurepoint',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departurepoint',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_departure_points', to='accounts.adminprofile'),
        ),
        migrations.AddField(
            model_name='departurepoint',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departurepoint',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departurepoint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('inactive', 'Inactive (transferred or removed)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='departurepoint',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_points', to='transport.rank'),
        ),
        migrations.RemoveField(
            model_name='departurepoint',
            name='area',
        ),
        migrations.RemoveField(
            model_name='departurepoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='departurepoint',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='departurepoint',
            name='name',
        ),
    ]
