# Generated by Django 5.2.17 on 2026-09-25 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_drivercomplaint_drivernotification_driverrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivernotification',
            name='link_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_notifications', to='transport.booking'),
        ),
        migrations.AddField(
            model_name='drivernotification',
            name='link_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_notifications', to='transport.trip'),
        ),
        migrations.AddField(
            model_name='drivernotification',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Optional: passenger_lat, passenger_lng, passenger_name, trip_code'),
        ),
    ]
