# Generated by Django 5.2.17 on 2026-09-20 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminprofile_rank'),
        ('transport', '0002_tripassetchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='walk_in_next_of_kin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='walk_in_next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='trip',
            name='engaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='engaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engaged_trips', to='accounts.operatorprofile'),
        ),
    ]
