# Generated by Django 5.2.17 on 2026-09-24 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_booking_walk_in_next_of_kin_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('has_complaint', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('driver_conduct', 'Driver behaviour'), ('safety', 'Safety concern'), ('punctuality', 'Punctuality'), ('vehicle_condition', 'Vehicle condition'), ('overcharging', 'Overcharging'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('resolved', 'Resolved — check your notifications'), ('escalated', 'Escalated to admin'), ('confirmed_incident', 'Confirmed safety incident'), ('dismissed', 'Dismissed')], default='submitted', max_length=30)),
                ('operator_response', models.TextField(blank=True)),
                ('admin_response', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='transport.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reviewed', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='transport.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
