# Generated by Django 5.2.17 on 2026-10-02 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_passwordresetcode'),
        ('transport', '0008_trip_assets_verified_at_trip_assets_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='companion_first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='companion_last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='group_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='transport.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='group_next_of_kin_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='group_next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='passenger_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('flagged', 'Flagged — needs admin review'), ('expired', 'Expired in queue')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='DriverAtRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminprofile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_memberships', to='accounts.driverprofile')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_memberships', to='transport.rank')),
            ],
            options={
                'ordering': ['rank__name'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'rank'), name='driver_rank_unique')],
            },
        ),
    ]
